#!/bin/bash

# This script symlinks all dotfiles to the home directory

if [ "$(basename "$(pwd)")" != "dotfiles" ]; then
	echo "Please run this script in dotfiles directory"
	exit 1
fi

home_dots=$(find . -name ".*" -type f -maxdepth 1 -exec basename {} \;)

# list of directories belonging in .config
config_dots=("kitty nvim yay dunst i3 i3status rofi")

# assert that all directories in config_dots exist
for d in $config_dots; do
	if [ ! -d "$d" ]; then
		echo "Directory $d does not exist"
		exit 1
	fi
done

# home dotfiles
for f in $home_dots; do
	echo "symlinking $(pwd)/$f to ~/$f"
	ln -s "$(pwd)/$f" ~/"$f"
done

# .configs
for d in $config_dots; do
	echo "symlinking $(pwd)/$d to ~/.config/$d"
	if [ -d ~/.config/"$d" ]; then
		rm -r ~/.config/"$d"
	fi
	ln -s "$(pwd)"/"$d" ~/.config/"$d"
done

# bins
echo "symlinking $(pwd)/bin to ~/.local/bin"
ln -s "$(pwd)/bin" ~/.local

##### SUDO LINKS REQUIRED PAST THIS POINT #####
if [ "$EUID" -ne 0 ]; then
	echo ""
	echo ""
	echo -e "\tPlease run this script as root to symlink btrbk and pacman snapshot hooks"
	echo ""
	echo ""
	exit 1
fi

# btrbk config
echo "symlinking $(pwd)/btrbk/btrbk.conf to /etc/btrbk.conf"
ln -s "$(pwd)/btrbk/btrbk.conf" /etc/btrbk/btrbk.conf

echo "symlinking $(pwd)/btrbk/btrbk.external.conf to /etc/btrbk.external.conf"
ln -s "$(pwd)/btrbk/btrbk.external.conf" /etc/btrbk/btrbk.external.conf

# pacman hooks
echo "symlinking $(pwd)/pacman to /etc/pacman.d/hooks"
ln -s "$(pwd)/pacman" /etc/pacman.d/hooks
