#!/bin/bash

# This script symlinks all dotfiles to the home directory

if [ "$(basename "$(pwd)")" != "dotfiles" ]; then
	echo "Please run this script in dotfiles directory"
	exit 1
fi

home_dots=$(find . -name ".*" -type f -maxdepth 1 -exec basename {} \;)

# list of directories belonging in .config
config_dots=("kitty nvim yay dunst")

# assert that all directories in config_dots exist
for d in $config_dots; do
	if [ ! -d "$d" ]; then
		echo "Directory $d does not exist"
		exit 1
	fi
done

for f in $home_dots; do
	echo "symlinking $(pwd)/$f to ~/$f"
	ln -s "$(pwd)/$f" ~/"$f"
done

for d in $config_dots; do
	echo "symlinking $(pwd)/$d to ~/.config/$d"
	if [ -d ~/.config/"$d" ]; then
		rm -r ~/.config/"$d"
	fi
	ln -s "$(pwd)"/"$d" ~/.config/"$d"
done

echo "symlinking $(pwd)/bin to ~/.local/bin"
ln -s "$(pwd)/bin" ~/.local
