#!/bin/bash

# This script symlinks all dotfiles to the home directory

if [ "$(basename "$(pwd)")" != "dotfiles" ]; then
	echo "Please run this script in dotfiles directory"
	exit 1
fi

home_dots=$(find . -name ".*" -type f -maxdepth 1)

config_dots=$(find .config -maxdepth 1 -mindepth 1)

for f in $home_dots; do
	echo "symlinking $(pwd)/$f to ~/$f"
	ln -s "$(pwd)/$f" ~/"$f"
done

for d in $config_dots; do
	dir_name=$(basename "$d")

	echo "symlinking $(pwd)/$d to ~/.config/$dir_name"
	ln -s "$(pwd)"/.config/"$dir_name" ~/.config/"$dir_name"
done

echo "symlinking $(pwd)/bin to ~/.local/bin"
ln -s "$(pwd)/bin" ~/.local
